server:
  port: 9909

page:
  path: "E:\\za\\软件工作区\\wdy\\wdy-master\\wdy-ui\\item\\"


spring:
  rabbitmq:
    host: 47.100.37.176
    port: 5672
    username: guest
    password: guest
    #    支持发布确认
    publisher-confirms: true
    #    支持发布返回
    publisher-returns: true
    listener:
      simple:
        #      采用手动应答
        acknowledge-mode: manual
        #        当前监听容器数
        concurrency: 1
        #        最大数
        max-concurrency: 1
        #        是否支持重试
        retry:
          enabled: false
  datasource:
    url: jdbc:mysql://47.100.37.176:3306/wdydb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1215855088@qq.com #QQ邮箱
    password: htwqtglfzbjejhdg #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致
  redis:
    host: 47.100.37.176
    password: "yang...."
    timeout: 8000
    port: 6379
    database: 0
  data:
    elasticsearch:
      #cluster-name: #默认为elasticsearch
      cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode（9200端口是http查询使用的。9300集群使用。这里使用9300.）
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wdy.product.model.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: ignored
      #驼峰下划线转换
      column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
